### ISSUE TITLE
Request For Grade

### ISSUE THREAD

**Issue by jmann-williams** [jmann-williams/animal-rescue-website#1]
@charlie-quinn

Thank you for the opportunity to let me submit the project. I know I didn't get the whole thing done, I got stuck up on the accessibility portion of the website, but I feel the grade I expect for the project is a C or B-. You are able to tab through the site, but I wasn't able to achieve what markbot was expecting.

**Comment by charlie-quinn** [comment]
✅ `This portion of your final assignment has been graded. A marking rubric has been sent to your college email address.`

⚠️`Reminder: please close this issue once it has been resolved.`
